services:
  bibi-bot-db:
    container_name: bibi-bot-db
    image: postgres:18-alpine
    restart: always
    volumes:
      - bibi-bot-pgdata:/var/lib/postgresql
      - ~/duplicati-volume/source/bibi-bot-db-pgbackup:/backups
    networks:
      - proxy
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
  bibi-bot-pgbackup:
    container_name: bibi-bot-pgbackup
    image: prodrigestivill/postgres-backup-local:18-alpine
    restart: always
    networks:
      - proxy
    volumes:
      - ~/duplicati-volume/source/bibi-bot-db-pgbackup:/backups
    links:
      - bibi-bot-db
    depends_on:
      - bibi-bot-db
    environment:
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_EXTRA_OPTS=-Fc
      - SCHEDULE=@every 6h
      - BACKUP_KEEP_DAYS=7
      - HEALTHCHECK_PORT=8080
  bibi-bot:
    container_name: bibi-bot
    depends_on:
      - bibi-bot-db
    links:
      - bibi-bot-db
    networks:
      - proxy
    build:
      context: ./
      dockerfile: Dockerfile
      target: prod
    restart: always
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}/${POSTGRES_DB}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.bibi-bot.entrypoints=websecure"
      - "traefik.http.routers.bibi-bot.tls.certresolver=letsencrypt"
      - "traefik.http.services.bibi-bot.loadbalancer.server.port=4000"

networks:
  proxy:
    external: false
    name: proxy

volumes:
  bibi-bot-pgdata:
    external: true
